### ISSUE TITLE
Encoding or interface problems

### ISSUE THREAD

**Issue by mrkaban** [markmal/freeship-plus-in-lazarus#37]
Forced again to raise the [topic](https://github.com/markmal/freeship-plus-in-lazarus/issues/35), since on Windows 10 x64 the same problem. version 4.1.1.159.

On Windows 7, I did not notice such a problem, so we can conclude that it was solved on this version of the OS.
![Снимок](https://user-images.githubusercontent.com/14289360/58268697-20d42180-7db0-11e9-9cfe-b539b08946de.jpg)
![Снимок2](https://user-images.githubusercontent.com/14289360/58268699-216cb800-7db0-11e9-9513-8a984485baa4.jpg)

**Comment by markmal** [comment]
I see forward slash there in the path. It is weird. Some Windows tolerate forward slash in path, some do not. I'll take a look.
What is edition of your Windows?

**Comment by mrkaban** [comment]
![Снимок](https://user-images.githubusercontent.com/14289360/58338963-d2d42200-7e72-11e9-819f-6c4ca6740a3f.jpg)

**Comment by mrkaban** [comment]
On Windows 7 64-bit program started without problems. There this problem is solved.

**Comment by markmal** [comment]
I've fixed the / problem, but not released the new version yet.

**Comment by markmal** [comment]
released 4.1.2

**Comment by mrkaban** [comment]
The same, launch error and no icons.

**Comment by markmal** [comment]
fixed more "/ issues"
released 4.1.2.168
please try again

**Comment by mrkaban** [comment]
The same, can you drop some log file?

**Comment by markmal** [comment]
Have you run install-usr.cmd ?
Please try to run uninstall-usr.cmd, then

Installation from ZIP
1. Create temporary directory
2. Copy FreeShip*.zip file into it and unzip it.
3. Run install-user.cmd

Could you find where is Themes directory? In Win10 it is in %HOME%\AppData\Roaming\FreeShip\

**Comment by mrkaban** [comment]
Yes, I just tried it. This folder is here "C:\Users\Acer\AppData\Roaming\FreeShip".

I attach the contents of this folder, suddenly help.
[FreeShip.zip](https://github.com/markmal/freeship-plus-in-lazarus/files/3223839/FreeShip.zip)

**Comment by mrkaban** [comment]
Previously deleted, then installed, and each action on behalf of the administrator performed, but still the same error.

**Comment by markmal** [comment]
in your zip Themes directory is empty. It should have subdirectories "Default" and "Original" and further tree of subdirectories and icons.
I am not sure why XCOPY did not copied this tree. 
the install-user.cmd should be run under regular user, not Administrator. 
It will install application into your %HOME%\FreeShip 

I have manually removed %HOME%\FreeShip and %HOME%\AppData\Roaming\FreeShip
Then unzipped installation zip into %HOME%\tmp\FreeShip
Then just double clicked install-user.cmd as normal user.
The FreeShip was successfully installed into my home and when run it I do not see any problem.

**Comment by mrkaban** [comment]
I unpacked it in C:\Users\Acer\tmp\FreeShip and launched install-user.cmd from this folder as an administrator. When starting from the same folder, the same error appears. Have you checked the program on this operating system?

**Comment by markmal** [comment]
Please run install-user.cmd regular way. Do not use "Run As Administrator".

**Comment by mrkaban** [comment]
That helped! Thank!

**Comment by mrkaban** [comment]
Added a program to my website about free software with an attendance of approximately 1500 people per day. He is in Russian, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0/%D1%81%D0%B0%D0%BF%D1%80/free-ship-plus-%D0%B2-lazarus.html).

**Comment by mrkaban** [comment]
Ticket can be closed! Thanks for the quick answers!

**Comment by markmal** [comment]
Thanks for the reference!
